### PR TITLE
Added dropdown list for activity groups

### PR DESCRIPTION
**Pull request by albaintor**
Hi,

I have added activity groups to your integration with drop down lists, instead of having activities in switches buttons.
I had to copy/paste your wrapper library files from pyUnfoldedCircleRemote into the component to make it work (and I removed the external lib from the manifest)

The library works as expected at this state. I let you tell me if it is okay for you

### CODE REVIEW

**Comment by albaintor** [comment]
Also I have moved the loading part to the coordinator instead of the switch entity because loaded data is useful for all entities and should be done before (this is what the coordinator is aimed for).
I have renamed the device to match user's one.

**Comment by JackJPowell** [comment]
Hi Albaintor,

Thanks for the contributions and interest in the project. I've finally been able to sit down and take a closer look at things. Looks like you and I were on the same page in adding the reconfigure support. I have that working in my local branch. The activity groups are a new thought though that I haven't considered. I like the idea but a couple of things to consider:

- The devs chose not to group activities by group in the UI. This could be temporary, but they did call it out specifically and didn't say it was coming in the future.
- I do like the 'Power Off' option! It is confusing when no activities are running though. It does sort of imply they are
- Would a better option be to provide a service that powers off all activity activities and optionally takes a group as input to only power those down? 
- Do the select options provide a way to show which activities in the group are running? The selected one makes sense. But what if you have more than one active? 
- Users that currently have activities defined as switches will have those entities no longer provided by the integration. I'm pretty sure they would also have to update any automations they had defined as well. 

Unlike the harmony integration which recently switched to using a select entity for its activities, I kept using switches due to the fact that multiple activities on the Remote Two can be active at once. And unless I'm mistaken, a select entity has no way to convey multiple 'on' states at the same time.

**Comment by JackJPowell** [comment]
A different topic, but I see you're investigating the web socket integration. I did briefly too but never got very far. 

The remote communicates to HA through a web socket so it definitely feels like the right answer. However, in my testing the WS connection would only stay active for a very short period of time before disconnecting. We could ping it to keep it active, but is that any better than polling for changes periodically? It seems like it would be at least a little as we'd only need a ping rather than a torrent of get requests.

Then there was pushing changes. I admittedly didn't look very hard but there wasn't an obvious way to do it and so I kept using the REST api. Anyway, I'm curious what you find. Could be some improvement there. Local Push!

**Comment by albaintor** [comment]
Hi,

actually if you include an activity in an activity group, you can’t have 2 activities running in the same group this is the main advantage of this as it will switch off the entities of the old activity before going to the new one. With customization (keep entities active if they are in both…). So we are in the same situation as harmony activities and so is the select appropriate for this. However if an activity is in no groups , it can be enabled apart and the switch is appropriate. This is the principle of the pull request I posted. 
on the other hand I am working on websocket : it is nearly working, a little more time is needed. But I can see improvements in the number of requests. The thing to deal with is sleeping state of the remote that can be VERY long.

**Comment by albaintor** [comment]
And indeed after the update users will have to deleted unavailable entities or recreate the integration

**Comment by albaintor** [comment]
I plan to commit an update during the weekend

**Comment by albaintor** [comment]
I have committed the changes : now the battery info + luminance + activities + software updates are updated through the websocket.
The luminance is disabled by default as it consumes a lot of requests : if the user enables it, I enable the event to be received in the websockets.
The problem now is the other sensors that won't be updated anymore (CPU, memory...): there are not available in the websocket which is normal (they change all the time). One must think to a solution to get them if user wants them (with polling necessarily)

**Comment by albaintor** [comment]
Hi again, I have found the solution : mixed polling if any entities require it, and push with websockets for the rest.
This is all committed and working. I let you review it

**Comment by JackJPowell** [comment]
You're right :)

image

It works well if you assume only a single media player entity is operating at a time. When you have more than one, they either overwrite the same media player entity in HA, or you create a new entity for each remote media player. And both of those options aren't good. Exposing the data through an array of extra state attributes may be worthwhile though.

Also, since all of my entities configured in the remote are also entities in home assistant, all of this data is duplicative. I can just pull this media info directly into Home Assistant from the nvidia shield or apple tv that the remote started playback on. 

It is pretty cool though!

**Comment by JackJPowell** [comment]
On the other hand, my remote's battery plummeted 25% in a couple of hours after creating the WS. It could be unrelated, but I'm now curious if this the intermittent polling wasn't gentler on the battery...

image

**Comment by albaintor** [comment]
About battery drain : have you enabled light luminance sensor ? if you disable it you have to restart integration (I didn't write code to dynamically restart the websocket when configuration changes) --> I wonder if this should not be more clever to get it through polling then (because with push you get about one request per second as luminance changes very often)
Otherwise to get (and verify) the benefits of the websocket over polling, you should also disable the other entities (cpu, memory...) except the dropdowns, the activity switches and the battery sensors (and restart the integration).
In that case there is no polling anymore.

I will do the same test to check after battery drain

About current media playing, I had the same thought. I see 2 possibilitiés :

1. Take the first media playing active and keep that one as long as the media is active
2. Create one media player entity per activity group : even in that case you may have severals and will have to pick one

This should not drain battery as the media playing is sent once when media starts (unless you play music it will happen more frequently)

Last thing to tryout : reduce the ping/pong delay of the websocket. I asked dev team on discord to get the timeout delay of the websocket. I could try to measure it on my own though

**Comment by albaintor** [comment]
Hi,

I have fixed several things :

- Websocket reconnection after remote reboot or sleeping
- Increased the ping/pong delay of websocket
- Reduced the unnecessary requests
- Fixed timeout during the initialization of the integration : many requests sent to the remote to load API data but at the end HA will cancel loading the last entities, especially for the remote entity
- Added a polling sensor to be aware if the integration does polling or not. Polling will be disabled if entities that use polling are all disabled
- Added attributes to the remote entity (I think you wondered how to display more data)
- Improved discovery settings based on mac address : this is the only key which is provided by zeroconf and that can be check against in user flow configuration. The benefit will be not to have already added devices to be discovered again
- Renamed the remote device to the one the user named : useful when you have more than one RC2 (which is my case)

Battery consumption seems right : I set up my remote to sleep after 30 minutes (max setting) and battery drains a lot with this setting without this integration. So it seems to be okay on that part :
image

**Comment by albaintor** [comment]
Hi again,
I have added media player entities to the integration (one per activity group)
image

**Review by JackJPowell — APPROVED** [review]

**Pull request merged**
