### PR TITLE
Unified intregration updated

### PR DESCRIPTION
**Pull request by albaintor**
Several modifications here :

- Handle of new  event types from the HA driver : unfoldedcircle/event/configure/(un)subscribe in order to send the new entities configured from HA side to the HA driver and update the remote
- Handle of unfoldedcircle/event/entities/(un)subscribe in order to send the specific events that concern only the submitted entities
- Rework of the setup flow to integrate the selection of entities, as well as the config flow after setup to modify the list of subscribed entities.
- Rework of the websocket interface initially loaded on the coordinator but problematic : no coordinator exist if no remote is configured, multiple coordinators so duplicate subscriptions if multiple remotes configured. Websocket is now instantiated as singleton from multiple places : from coordinator, from config flow and especially during zeroconf config flow which is useful to get an instance BEFORE the user starts the config flow and get events then.
- Some updates to support webconfigurator, and update of the regex for Remote 3 (TBC)
- Other modifications I don't remember :-)

### CODE REVIEW

**Comment by JackJPowell** [comment]
Did you rebase from main? Most of these changes are already merged but are showing as new in your pull request.

**Comment by albaintor** [comment]
Strange, I have merged your main branch into my unified_integration branch...

**Comment by JackJPowell** [comment]
Looks like it's primarily the 'merged from main' commit 7cda4c81b6399ab1dde57afc860eeaf1ea6c63cb

They are showing as additions in the pull but they already exist in main

**Comment by JackJPowell** [comment]
I really like the config flow addition. The menu of options is really slick. I don't think I've seen that in home assistant before. 

This pull request however is lost. I'm not sure what happened along the way but it's too hard to make sense of things. But, I was able to pretty easily just do a manual compare and merge.

The branch `feature/unified-integration` is fully up to date with all of your changes plus my recent changes adding in dock device support and a bunch of cleanup/remote 3 prep that were released last week with v0.11.0. I also moved the hard coded string to translations and made several updates to comments, english translations, and formatting. 

If the last changes you made were included in this most recent commit, you should be able to switch to this branch `feature/unified-integration` and resume working right where you left off.

**Pull request closed without merging**
